In [24]:
def read_column(filepath,column_name):
    f = open(filepath)
    list_of_my_csv = []
    for row in f:
        row = row.replace('\n','')
        row = row.strip()
        list_of_my_csv.append(row.split(','))
    dict={}
    First_Row = list_of_my_csv.pop(0)
    for i in First_Row:
        dict[i]=First_Row.index(i)
    required_list=[item[dict[column_name]] for item in list_of_my_csv]
    return required_list
  
try:
    required_column=input('Enter name of the column from the following options: \n 1) gender \n 2) parental level of education \n 3) lunch \n 4) test preparation course \n 5) math score \n 6) reading score \n 7) writing score \n \n')
    print("\n ",read_column('H:\ADS\S1\PFDS\Assignment 1\exams.csv',required_column))
except:
    print("Please enter only from the above mentioned options")

print("Program Ends")

Enter name of the column from the following options:
 1) gender
 2) parental level of education
 3) lunch
 4) test preparation course
 5) math score
 6) reading score
 7) writing score

 math score

  ['67', '40', '59', '77', '78', '63', '62', '93', '63', '47', '99', '80', '77', '74', '81', '69', '58', '54', '23', '39', '83', '58', '71', '44', '46', '51', '53', '71', '74', '33', '87', '78', '40', '65', '79', '68', '57', '67', '58', '98', '54', '77', '87', '58', '100', '60', '64', '65', '68', '60', '65', '52', '74', '36', '57', '56', '67', '88', '42', '68', '76', '58', '69', '77', '83', '49', '71', '47', '79', '60', '56', '57', '49', '79', '71', '71', '47', '72', '78', '54', '46', '31', '51', '78', '32', '53', '63', '97', '56', '72', '57', '74', '81', '94', '81', '58', '95', '45', '63', '60', '54', '75', '79', '66', '47', '70', '82', '56', '92', '30', '79', '41', '63', '43', '77', '76', '49', '59', '59', '76', '55', '78', '51', '41', '74', '62', '77', '45', '100', '83', '77', '66', '65', '62', '55', '73', '73', '48', '52', '60', '68', '65', '86', '55', '80', '51', '63', '60', '100', '46', '67', '54', '63', '68', '54', '43', '64', '92', '82', '84', '84', '65', '83', '70', '66', '71', '66', '57', '86', '80', '62', '71', '57', '69', '83', '50', '55', '55', '83', '89', '51', '48', '84', '69', '75', '91', '76', '63', '73', '52', '58', '33', '68', '77', '64', '39', '50', '53', '54', '74', '50', '55', '77', '49', '66', '77', '74', '85', '77', '64', '61', '97', '66', '62', '64', '55', '53', '71', '66', '68', '89', '65', '43', '79', '99', '82', '35', '61', '76', '94', '75', '81', '35', '76', '58', '100', '53', '82', '76', '83', '72', '76', '66', '63', '36', '68', '40', '68', '56', '74', '53', '88', '67', '60', '51', '53', '80', '69', '64', '80', '58', '39', '64', '61', '90', '73', '73', '67', '57', '65', '71', '59', '74', '93', '85', '76', '58', '72', '40', '75', '85', '100', '53', '40', '49', '77', '82', '55', '62', '69', '78', '71', '59', '60', '43', '77', '50', '56', '69', '47', '43', '48', '55', '73', '71', '54', '66', '63', '66', '79', '73', '36', '50', '87', '71', '85', '58', '86', '64', '83', '58', '59', '40', '82', '87', '62', '76', '63', '58', '61', '78', '78', '56', '96', '48', '70', '43', '45', '58', '70', '60', '52', '61', '55', '80', '63', '79', '74', '46', '72', '58', '47', '68', '68', '65', '50', '48', '58', '71', '58', '66', '44', '51', '78', '72', '60', '55', '64', '57', '70', '84', '66', '56', '59', '87', '73', '85', '49', '82', '80', '48', '85', '70', '89', '72', '80', '43', '54', '82', '74', '63', '47', '13', '67', '57', '64', '85', '70', '90', '53', '74', '61', '55', '65', '77', '74', '94', '54', '52', '73', '81', '62', '55', '55', '61', '75', '79', '70', '72', '38', '57', '76', '45', '77', '40', '78', '63', '83', '55', '88', '82', '86', '61', '78', '67', '83', '68', '53', '91', '67', '53', '86', '75', '55', '93', '62', '83', '73', '57', '70', '55', '65', '76', '59', '74', '65', '89', '71', '63', '57', '56', '49', '28', '69', '49', '67', '74', '47', '63', '73', '91', '80', '66', '52', '65', '83', '80', '68', '68', '62', '76', '77', '83', '71', '86', '93', '60', '57', '84', '66', '85', '57', '41', '75', '65', '78', '26', '71', '86', '89', '53', '87', '71', '77', '43', '88', '86', '45', '69', '65', '81', '90', '78', '71', '75', '70', '54', '49', '80', '78', '89', '65', '78', '69', '49', '50', '79', '89', '48', '63', '88', '66', '45', '62', '74', '82', '83', '60', '66', '76', '75', '77', '82', '63', '70', '84', '68', '56', '37', '49', '100', '83', '92', '71', '72', '37', '35', '69', '65', '56', '40', '60', '57', '58', '74', '77', '66', '62', '29', '70', '67', '81', '56', '61', '47', '88', '51', '68', '68', '47', '84', '69', '52', '80', '100', '53', '59', '78', '84', '52', '81', '90', '63', '100', '56', '46', '75', '46', '42', '77', '40', '69', '43', '69', '89', '44', '82', '72', '64', '89', '58', '63', '54', '83', '57', '52', '75', '67', '58', '63', '49', '38', '74', '69', '77', '40', '96', '85', '85', '72', '63', '58', '58', '51', '100', '77', '63', '64', '100', '66', '87', '73', '69', '62', '40', '55', '77', '63', '85', '30', '82', '81', '92', '50', '54', '76', '60', '45', '80', '52', '90', '53', '92', '63', '71', '64', '67', '63', '63', '59', '49', '75', '34', '53', '63', '75', '63', '70', '61', '74', '57', '41', '87', '69', '69', '58', '47', '78', '54', '36', '94', '68', '90', '57', '96', '68', '52', '90', '71', '58', '41', '43', '85', '71', '72', '70', '89', '92', '80', '80', '56', '93', '49', '59', '64', '73', '82', '48', '51', '38', '45', '83', '45', '66', '60', '49', '80', '75', '57', '25', '90', '63', '100', '76', '52', '81', '90', '83', '61', '79', '52', '62', '85', '74', '83', '78', '41', '77', '95', '50', '74', '74', '70', '61', '94', '66', '83', '75', '56', '66', '61', '70', '57', '78', '62', '64', '55', '72', '49', '62', '76', '73', '72', '85', '71', '28', '41', '78', '48', '38', '91', '71', '84', '63', '70', '48', '68', '84', '61', '62', '66', '52', '68', '62', '90', '42', '74', '62', '56', '64', '79', '44', '69', '53', '74', '49', '57', '61', '65', '51', '49', '56', '65', '70', '91', '48', '94', '77', '59', '57', '76', '65', '75', '70', '79', '100', '83', '70', '97', '33', '38', '46', '13', '85', '79', '76', '53', '68', '67', '100', '54', '72', '91', '87', '66', '65', '41', '67', '94', '57', '89', '77', '57', '72', '98', '87', '61', '85', '81', '74', '98', '86', '85', '68', '66', '75', '79', '59', '60', '69', '49', '62', '70', '71', '71', '50', '52', '75', '51', '64', '65', '99', '60', '70', '77', '37', '73', '53', '67', '67', '51', '64', '55', '55', '86', '71', '71', '51', '75', '45', '59', '64', '78', '59', '80', '68', '77', '66', '26', '80', '48', '52', '54', '59', '77', '64', '83', '70', '72', '83', '52', '53', '55', '65', '60', '64', '71', '61', '61', '65', '71', '48', '75', '54', '70', '91', '33', '45', '45', '62', '92', '74', '81', '76', '57', '63', '57', '46', '49', '54', '89', '77', '46', '66', '48', '83', '69', '73', '43', '91', '49', '87', '46', '63', '100', '86', '55', '84', '39', '67', '85', '64', '81', '78', '59', '74', '31', '54', '51', '57', '39', '64', '69', '58', '63', '74', '78', '78', '75', '70', '67', '87', '69', '58', '86', '73', '85', '32', '73', '65']
Program Ends

In [ ]:
def value_counts(elements):
    list_of_count=[[x,elements.count(x)] for x in set(elements)]
    d={key: value for (key, value) in list_of_count}
    for k,v in d.items():
        print(k,": ",v)
value_counts(read_column('H:\ADS\S1\PFDS\Assignment 1\exams.csv',required_column))

In [23]:
def argmax(list_of_numbers):
    lowest=-1000
    for i in list_of_numbers:
        if i>lowest:
            lowest=i
            index_of_maximum_value_in_the_list = list_of_numbers.index(i)
    return index_of_maximum_value_in_the_list


if required_column == 'math score' or 'reading score' or 'writing score':
    numerical_list = [int(i) for i in read_column('H:\ADS\S1\PFDS\Assignment 1\exams.csv',required_column)]
    print("The index of maximum value in our list is: ",argmax(numerical_list))
else:
    print("The selected column is not is numerical hence max can't be found")

The index of maximum value in our list is:  96